[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true

optimizer = true
optimizer_runs = 200

[profile.default.fmt]
single-line-func-calls = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]